Repository ComposioHQ/composio, pull requests merged in 2024-05, with the labels that each got.

#58 Remove old code
  .github/workflows/common.yml
  .pylintrc
  composio/__init__.py
  composio/cli/apps.py
  composio/cli/connections.py
  composio/cli/context.py
  composio/cli/integrations.py
  composio/cli/triggers.py
  composio/cli/whoami.py
  composio/client/__init__.py
  composio/client/enums.py
  composio/composio_cli.py
  composio/sdk/__init__.py
  composio/sdk/core.py
  composio/sdk/enums.py
  composio/sdk/exceptions.py
  composio/sdk/http_client.py
  composio/sdk/sdk.py
  composio/sdk/shared.py
  composio/sdk/shared_utils.py
  composio/sdk/storage.py
  composio/sdk/utils.py
  composio/tools/local/__init__.py
  composio/tools/local/file/__init__.py
  composio/tools/local/file/tool.py
  composio/utils/shared.py
  examples/__init__.py
  examples/autogen_demo.py
  examples/claude_demo.py
  examples/crewai-scheduler.py
  examples/crewai_demo.py
  examples/griptape_demo.py
  examples/julep_demo.py
  examples/langchain_demo.py
  examples/lyzr_demo.py
  examples/openai_assistant_demo.py
  examples/openai_demo.py
  plugins/autogen/composio_autogen/toolset.py
  plugins/claude/composio_claude/__init__.py
  plugins/claude/composio_claude/toolset.py
  plugins/griptape/composio_griptape/toolset.py
  plugins/langchain/composio_langchain/pydantic_utils.py
  plugins/langchain/composio_langchain/toolset.py
  plugins/langchain/langchain_demo.py
  plugins/lyzr/composio_lyzr/toolset.py
  plugins/openai/assistant.py
  plugins/openai/composio_openai/toolset.py
  plugins/openai/openai_assistant_demo.py
  plugins/openai/openai_demo.py
  tests/test_autogen.py
  tests/test_crewai.py
  tests/test_langchain.py
  tox.ini
Labels: documentation, enhancement, Tests, Review effort [1-5]: 5

#59 Guides
  AUTHORS.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/development.md
  docs/imgs/banner.png
  setup.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#62 Fix slack default connector issue
  composio/cli/add.py
  composio/client/__init__.py
Labels: Bug fix, Review effort [1-5]: 3

#63 Fix auth scheme validation
  composio/cli/add.py
  composio/cli/triggers.py
  composio/client/__init__.py
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#70 Entity id argument usage on plugins
  plugins/autogen/composio_autogen/toolset.py
  plugins/claude/composio_claude/toolset.py
  plugins/griptape/composio_griptape/toolset.py
  plugins/julep/composio_julep/toolset.py
  plugins/langchain/composio_langchain/toolset.py
  plugins/lyzr/composio_lyzr/toolset.py
  plugins/openai/composio_openai/toolset.py
Labels: enhancement, Review effort [1-5]: 3

#74 Fixed Julep SDK
  plugins/julep/composio_julep/toolset.py
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#64 WIP
  composio/client/enums.py
  composio/client/local_handler.py
  composio/local_tools/action.py
  composio/local_tools/greptile/__init__.py
  composio/local_tools/greptile/codequery.py
  composio/local_tools/greptile/test_codequery.py
  composio/local_tools/greptile/tool.py
  composio/local_tools/local_workspace/cmd_manager/actions/__init__.py
  composio/local_tools/local_workspace/cmd_manager/actions/base_class.py
  composio/local_tools/local_workspace/cmd_manager/actions/clone_github.py
  composio/local_tools/local_workspace/cmd_manager/actions/cmds.py
  composio/local_tools/local_workspace/cmd_manager/actions/edit_cmd.py
  composio/local_tools/local_workspace/cmd_manager/actions/run_cmd.py
  composio/local_tools/local_workspace/cmd_manager/actions/scroll_cmds.py
  composio/local_tools/local_workspace/cmd_manager/actions/search_cmds.py
  composio/local_tools/local_workspace/cmd_manager/cmd_manager_tool.py
  composio/local_tools/local_workspace/commons/command_runner_model.py
  composio/local_tools/local_workspace/commons/history_processor.py
  composio/local_tools/local_workspace/commons/local_docker_workspace.py
  composio/local_tools/local_workspace/commons/utils.py
  composio/local_tools/local_workspace/config/agent_task_data.yaml
  composio/local_tools/local_workspace/config/agent_task_data_2.yaml
  composio/local_tools/local_workspace/config/command_runner_config.py
  composio/local_tools/local_workspace/config/commands.yaml
  composio/local_tools/local_workspace/config/commands/README.md
  composio/local_tools/local_workspace/config/commands/cursor_default.sh
  composio/local_tools/local_workspace/config/commands/cursor_edit_linting.sh
  composio/local_tools/local_workspace/config/default.yaml
  composio/local_tools/local_workspace/history_keeper/actions/__init__.py
  composio/local_tools/local_workspace/history_keeper/actions/get_workspace_history.py
  composio/local_tools/local_workspace/history_keeper/history_keeper_tool.py
  composio/local_tools/local_workspace/repo_map/actions/.aider.tags.cache.v3/cache.db
  composio/local_tools/local_workspace/task/default.yaml
  composio/local_tools/local_workspace/test/check_implementation.py
  composio/local_tools/local_workspace/workspace/actions/__init__.py
  composio/local_tools/local_workspace/workspace/actions/base_workspace_action.py
  composio/local_tools/local_workspace/workspace/actions/create_workspace.py
  composio/local_tools/local_workspace/workspace/actions/setup_github_repo.py
  composio/local_tools/local_workspace/workspace/actions/workspace_setup.py
  composio/local_tools/local_workspace/workspace/actions/workspace_status.py
  composio/local_tools/local_workspace/workspace/workspace_tool.py
  composio/local_tools/mathematical/calculator.py
  composio/local_tools/tool.py
  examples/benchmark/Readme.md
  examples/benchmark/evaluation.py
  examples/requirements.txt
  examples/swe/benchmark_script.py
  examples/swe/task_config.yaml
  examples/swe/task_config_sample.yaml
  examples/swe/try-swe.py
  langchain_math.py
  plugins/claude/demo.ipynb
  setup.py
  start_cli.py
  tests/test_cli/test_login.py
  tox.ini
Labels: documentation, enhancement, Review effort [1-5]: 3

#79 feat: add RAG and web tool
  composio/client/enums.py
  composio/client/local_handler.py
  composio/local_tools/ragtool/__init__.py
  composio/local_tools/ragtool/ragtool.py
  composio/local_tools/webtool/WebTool.py
  composio/local_tools/webtool/__init__.py
Labels: enhancement, other, Review effort [1-5]: 3

#80 Added examples
  examples/CompetitiorResearcher/CompetitiorResearcher.py
  examples/GithubToTrello/GithubToTrello.py
  examples/InvestmentAnalysis/InvestmentAnalysis.py
  examples/NewsSummary/NewsSummary.py
  examples/ResearchAssistant/ResearchAssistant.py
  examples/TodoToCalendar/TodoToCalendar.py
  examples/requirements.txt
Labels: enhancement, Review effort [1-5]: 4
