Repository ComposioHQ/composio, pull requests merged in 2024-07, with the labels that each got.

#256 Update benchmarking scaffold
  python/composio/tools/env/host/shell.py
  python/composio/tools/local/shelltool/git_cmds/actions/clone_github.py
  python/composio/tools/toolset.py
  python/swe/composio_swe/benchmark/__init__.py
  python/swe/composio_swe/benchmark/complete_eval_workflow.sh
  python/swe/composio_swe/benchmark/constants.py
  python/swe/composio_swe/benchmark/get_score_card.py
  python/swe/composio_swe/benchmark/run_eval.md
  python/swe/composio_swe/benchmark/run_evaluation.py
  python/swe/composio_swe/benchmark/setup_test_bed.py
  python/swe/composio_swe/benchmark/visualize.py
  python/swe/composio_swe/scaffold/_scaffold.py
  python/swe/composio_swe/scaffold/templates/crewai/agent.template
  python/swe/composio_swe/scaffold/templates/crewai/benchmark.template
  python/swe/composio_swe/scaffold/templates/crewai/main.template
  python/swe/composio_swe/scaffold/templates/crewai/prompts.template
Labels: enhancement, Tests, Review effort [1-5]: 4

#249 add cn readme
  README-CN.md
  README.md
Labels: documentation, Review effort [1-5]: 2

#210 docs: update twitter.mdx
  docs/apps/twitter.mdx
Labels: documentation, Review effort [1-5]: 1

#269 fix: auto get connected accounts in entity.execute()
  js/src/sdk/client/services.gen.ts
  js/src/sdk/client/types.gen.ts
  js/src/sdk/index.ts
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#270 chore: bump js sdk to v0.1.5
  js/package.json
Labels: enhancement, Review effort [1-5]: 1

#268 Add support for reading exit codes on shells
  python/composio/tools/env/constants.py
  python/composio/tools/env/docker/scripts/commands/edit.sh
  python/composio/tools/env/docker/shell.py
  python/composio/tools/env/docker/workspace.py
  python/composio/tools/env/host/shell.py
  python/composio/tools/local/shelltool/file_cmds/actions/base_file_cmds.py
  python/composio/tools/local/shelltool/file_cmds/actions/edit_cmd.py
  python/composio/tools/local/shelltool/file_cmds/actions/scroll_cmds.py
  python/composio/tools/local/shelltool/find_cmds/actions/search_cmds.py
  python/composio/tools/local/shelltool/git_cmds/actions/clone_github.py
  python/composio/tools/local/shelltool/git_cmds/actions/get_patch.py
  python/composio/tools/local/shelltool/git_cmds/actions/git_tree.py
  python/composio/tools/local/shelltool/shell_exec/actions/exec.py
  python/composio/tools/local/shelltool/utils.py
  python/tests/test_tools/test_local/__init__.py
  python/tests/test_tools/test_local/test_workspace.py
Labels: Review effort [1-5]: 4

#267 Update SWE Readme
  python/swe/DEVELOPMENT.md
  python/swe/README.md
  python/swe/composio_swe/scaffold/templates/crewai/benchmark.template
Labels: documentation, Review effort [1-5]: 3

#272 docs: add Japanese README
  README-CN.md
  README-JP.md
  README.md
Labels: documentation, Review effort [1-5]: 2

#277 feat: Spider scraper & crawler tool
  python/composio/client/enums/_action.py
  python/composio/client/enums/_app.py
  python/composio/tools/local/__init__.py
  python/composio/tools/local/spidertool/__init__.py
  python/composio/tools/local/spidertool/actions/__init__.py
  python/composio/tools/local/spidertool/actions/crawl.py
  python/composio/tools/local/spidertool/actions/scrape.py
  python/composio/tools/local/spidertool/tool.py
Labels: enhancement, Review effort [1-5]: 3

#286 feat:slack-agent ollama was added
  python/examples/slack_bot_agent/slack_agent_ollama/.env.example
  python/examples/slack_bot_agent/slack_agent_ollama/main.py
  python/examples/slack_bot_agent/slack_agent_ollama/readme.md
  python/examples/slack_bot_agent/slack_agent_ollama/requirements.txt
  python/examples/slack_bot_agent/slack_agent_ollama/setup.sh
Labels: documentation, enhancement, Review effort [1-5]: 4

#290 Update benchmark to pass issue subset
  python/swe/swekit/benchmark/docker_utils/THIRD-PARTY-LICENSE
  python/swe/swekit/benchmark/docker_utils/__init__.py
  python/swe/swekit/benchmark/docker_utils/docker/Dockerfile.swe_agent
  python/swe/swekit/benchmark/docker_utils/docker_file_generator/__init__.py
  python/swe/swekit/benchmark/docker_utils/docker_file_generator/const.py
  python/swe/swekit/benchmark/docker_utils/docker_file_generator/context_manager.py
  python/swe/swekit/benchmark/docker_utils/docker_file_generator/docker_file_generator.py
  python/swe/swekit/benchmark/docker_utils/docker_file_generator/evaluate_instance.py
  python/swe/swekit/benchmark/docker_utils/docker_file_generator/run_docker.py
  python/swe/swekit/benchmark/docker_utils/docker_file_generator/utils.py
  python/swe/swekit/benchmark/docker_utils/evaulate_on_docker.py
  python/swe/swekit/benchmark/docker_utils/scripts/build_docker_images.sh
  python/swe/swekit/benchmark/docker_utils/scripts/docker_push.sh
  python/swe/swekit/benchmark/docker_utils/templates/Dockerfile.base
  python/swe/swekit/benchmark/docker_utils/templates/Dockerfile.pyenv_instance
  python/swe/swekit/benchmark/docker_utils/templates/Dockerfile.swe
  python/swe/swekit/benchmark/docker_utils/templates/getconda.sh
  python/swe/swekit/benchmark/docker_utils/templates/install_composio.sh
  python/swe/swekit/benchmark/run_evaluation.py
  python/swe/swekit/benchmark/utils.py
  python/swe/swekit/scaffold/templates/crewai/benchmark.template
Labels: enhancement, Tests, Review effort [1-5]: 5

#287 Fix swe errors
  python/composio/tools/env/docker/workspace.py
  python/swe/swekit/scaffold/templates/crewai/main.template
Labels: Review effort [1-5]: 2, Bug fix

#299 Add integration by id function
  python/composio/client/collections.py
Labels: enhancement, Review effort [1-5]: 2

#300 Update .gitattributes
  .gitattributes
Labels: Review effort [1-5]: 1, Configuration changes

#301 Update README.md
  README.md
Labels: documentation, Review effort [1-5]: 1

#313 feat: return value from _handle_callback for playground
  python/composio/client/collections.py
Labels: enhancement, Review effort [1-5]: 2

#297 Fix optional handling
  python/composio/utils/shared.py
Labels: Review effort [1-5]: 2, Bug fix

#304 Fix toolset file output
  python/composio/tools/toolset.py
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#316 Benchmarks changes to run on E2B/Fly.io
  python/composio/tools/env/docker/scripts/commands/defaults.sh
  python/swe/swekit/benchmark/run_evaluation.py
  python/swe/swekit/benchmark/utils.py
  python/tests/test_tools/test_local/test_workspace.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#321 fix local tools
  python/composio/client/enums/_action.py
  python/composio/client/enums/_trigger.py
  python/composio/tools/local/base/action.py
  python/composio/tools/local/base/utils/grep_utils.py
  python/composio/tools/local/base/utils/repomap.py
  python/composio/tools/local/codeformat/actions/code_format.py
  python/composio/tools/local/codegrep/actions/grep_code.py
  python/composio/tools/local/codeindex/actions/create_index.py
  python/composio/tools/local/codeindex/actions/search_index.py
  python/composio/tools/local/codemap/actions/__init__.py
  python/composio/tools/local/codemap/actions/delete_repomap.py
  python/composio/tools/local/codemap/actions/get_rankedtags.py
  python/composio/tools/local/codemap/actions/get_repomap.py
  python/composio/tools/local/codemap/actions/get_repostructure.py
  python/composio/tools/local/codemap/actions/init_repomap.py
  python/composio/tools/local/codemap/tool.py
  python/composio/tools/local/filetool/actions/read_file.py
  python/composio/tools/local/filetool/actions/write_file.py
  python/composio/tools/local/ragtool/actions/rag_add_request.py
  python/composio/tools/local/ragtool/actions/rag_query.py
  python/composio/tools/local/spidertool/actions/crawl.py
  python/composio/tools/local/webtool/actions/scrape_website_element.py
  python/plugins/langchain/langchain_demo.py
  python/swe/examples/crewai_agent/agent.py
  python/swe/examples/crewai_agent/benchmark.py
  python/swe/examples/crewai_agent/inputs.py
  python/swe/examples/crewai_agent/main.py
  python/swe/examples/crewai_agent/prompts.py
  python/tox.ini
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#323 chore: remove Error checking file response print statement
  python/composio/tools/toolset.py
Labels: enhancement, Review effort [1-5]: 1

#327 Fix/rag agent
  python/examples/pr_agent/pr_agent_autogen/main.py
  python/examples/rag_agent/.env.example
  python/examples/rag_agent/main.py
  python/examples/rag_agent/readme.md
  python/examples/rag_agent/requirements.txt
  python/examples/rag_agent/setup.sh
  python/examples/scheduler_agent/scheduler_agent_autogen/.env.example
  python/examples/scheduler_agent/scheduler_agent_autogen/main.py
  python/examples/scheduler_agent/scheduler_agent_autogen/readme.md
  python/examples/scheduler_agent/scheduler_agent_autogen/setup.sh
  python/examples/scheduler_agent/scheduler_agent_langchain/.env.example
  python/examples/scheduler_agent/scheduler_agent_langchain/main.py
  python/examples/scheduler_agent/scheduler_agent_langchain/readme.md
  python/examples/scheduler_agent/scheduler_agent_langchain/setup.sh
  python/examples/scheduler_agent/scheduler_agent_llamaindex/.env.example
  python/examples/scheduler_agent/scheduler_agent_llamaindex/main.py
  python/examples/scheduler_agent/scheduler_agent_llamaindex/readme.md
  python/examples/scheduler_agent/scheduler_agent_llamaindex/setup.sh
Labels: Review effort [1-5]: 4

#331 update: Removed unneccessary code in news summary docs
  docs/guides/python/news-summary.mdx
Labels: documentation, enhancement, Review effort [1-5]: 2

#343 added exclude none in serialiser
  python/composio/tools/toolset.py
Labels: Review effort [1-5]: 2, Bug fix

#319 Add new file tool without shell
  python/composio/client/enums/_action.py
  python/composio/tools/env/base.py
  python/composio/tools/env/docker/scripts/commands/edit.sh
  python/composio/tools/env/filemanager/__init__.py
  python/composio/tools/env/filemanager/file.py
  python/composio/tools/env/filemanager/manager.py
  python/composio/tools/env/host/workspace.py
  python/composio/tools/local/filetool/actions/__init__.py
  python/composio/tools/local/filetool/actions/base_action.py
  python/composio/tools/local/filetool/actions/chwdir.py
  python/composio/tools/local/filetool/actions/create_file.py
  python/composio/tools/local/filetool/actions/edit_file.py
  python/composio/tools/local/filetool/actions/find_file.py
  python/composio/tools/local/filetool/actions/list_files.py
  python/composio/tools/local/filetool/actions/open_file.py
  python/composio/tools/local/filetool/actions/read_file.py
  python/composio/tools/local/filetool/actions/scroll_file.py
  python/composio/tools/local/filetool/actions/search_word.py
  python/composio/tools/local/filetool/actions/write_file.py
  python/composio/tools/local/filetool/tool.py
  python/composio/utils/shared.py
  python/swe/examples/crewai_agent/agent.py
  python/tests/test_tools/test_local/test_workspace.py
Labels: enhancement, Review effort [1-5]: 4, Bug fix, other

#342 fix: use getEnvVariable function to get variables for cloudflare
  js/src/sdk/base.toolset.ts
  js/src/sdk/index.ts
  js/src/utils/shared.ts
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#347 Pass scope for oauth
  python/composio/cli/add.py
Labels: enhancement, Review effort [1-5]: 2

#337 feat: add support for configuring BASE_URL using COMPOSIO_BASE_URL env
  js/package.json
  js/src/sdk/index.ts
Labels: enhancement, Review effort [1-5]: 2

#344 Update sql query tool
  python/composio/tools/local/sqltool/actions/sql_query.py
Labels: enhancement, Review effort [1-5]: 2, Error handling

#349 fix docs - env variables, default model and init code
  docs/guides/javascript/interpreter-agent.mdx
  docs/guides/python/rag_agent.mdx
  docs/guides/python/research-assistant.mdx
  docs/javascript/langchain.mdx
  js/examples/langchain/demo.mjs
  js/examples/langchain/demo.ts
  js/examples/langchain/sample.mjs
  python/examples/image_search/image_search_crewai/main.py
  python/examples/image_search/image_search_langchain/image_search_frontend.py
  python/examples/image_search/image_search_langchain/main.py
  python/examples/image_search/image_search_langgraph/main.py
  python/examples/image_search/image_search_llamaindex/main.py
  python/examples/local_tools/autogen_math.py
  python/examples/miscellaneous/gmail_send_attachment_crew.py
  python/examples/pr_agent/pr_agent_crewai/main.py
  python/examples/pr_agent/pr_agent_langchain/main.py
  python/examples/pr_agent/pr_agent_llama_index/main.py
  python/plugins/autogen/README.md
  python/plugins/autogen/autogen_demo.py
  python/plugins/julep/README.md
  python/plugins/julep/julep_demo.py
  python/plugins/langchain/langchain_demo.py
  python/swe/examples/crewai_agent/agent.py
Labels: documentation, enhancement, Review effort [1-5]: 3

#350 fix docs layout
  docs/guides/casestudy/research-assistant.mdx
  docs/guides/examples/introduction.ipynb
  docs/guides/faqs/install.mdx
  docs/guides/starterprojects/gallery.mdx
  docs/guides/tutorials/install.mdx
  docs/introduction/intro/resources/ai.mdx
  docs/introduction/pricing/pricing.mdx
  docs/introduction/pricing/startups-program.mdx
  docs/mint.json
  docs/python/trigger.mdx
  docs/sdk/composio/client/endpoints.mdx
  docs/sdk/composio/client/enums.mdx
  docs/sdk/composio/client/exceptions.mdx
  docs/sdk/composio/client/http.mdx
  docs/sdk/composio/client/index.mdx
  docs/sdk/composio/client/local_handler.mdx
  docs/sdk/composio/constants.mdx
  docs/sdk/composio/exceptions.mdx
  docs/sdk/composio/storage/base.mdx
  docs/sdk/composio/storage/index.mdx
  docs/sdk/composio/storage/user.mdx
  docs/sdk/composio/tools/index.mdx
  docs/sdk/composio/tools/schema.mdx
  docs/sdk/composio/utils/decorators.mdx
  docs/sdk/composio/utils/git.mdx
  docs/sdk/composio/utils/index.mdx
  docs/sdk/composio/utils/shared.mdx
  docs/sdk/composio/utils/url.mdx
  docs/sdk/readme.txt
Labels: documentation, Review effort [1-5]: 2

#257 add slack-calndar agent
  python/examples/slack_calendar_agent/.env.example
  python/examples/slack_calendar_agent/Readme.md
  python/examples/slack_calendar_agent/agents.py
  python/examples/slack_calendar_agent/images/cute-llama_2.webp
  python/examples/slack_calendar_agent/images/slack_calendar_flow.png
  python/examples/slack_calendar_agent/main.py
  python/examples/slack_calendar_agent/poetry.lock
  python/examples/slack_calendar_agent/pyproject.toml
  python/examples/slack_calendar_agent/setup.sh
Labels: documentation, enhancement, Review effort [1-5]: 4

#240 Adding Podcast summarizer Agent
  cookbook/Podcast_summarizer_Agents/LICENSE
  cookbook/Podcast_summarizer_Agents/Podcast_Summarizer_AI_Agent.py
  cookbook/Podcast_summarizer_Agents/README.md
  cookbook/Podcast_summarizer_Agents/Tools/__init__.py
  cookbook/Podcast_summarizer_Agents/Tools/__pycache__/__init__.cpython-312.pyc
  cookbook/Podcast_summarizer_Agents/Tools/__pycache__/audio_trancriber.cpython-312.pyc
  cookbook/Podcast_summarizer_Agents/Tools/__pycache__/audio_trancriber_tool.cpython-312.pyc
  cookbook/Podcast_summarizer_Agents/Tools/__pycache__/composio_slack.cpython-312.pyc
  cookbook/Podcast_summarizer_Agents/Tools/__pycache__/composio_slack_tool.cpython-312.pyc
  cookbook/Podcast_summarizer_Agents/Tools/audio_trancriber.py
  cookbook/Podcast_summarizer_Agents/Tools/composio_slack.py
  cookbook/Podcast_summarizer_Agents/__init__.py
  cookbook/Podcast_summarizer_Agents/__pycache__/Podcast_Summarizer_AI_Agent.cpython-312.pyc
  cookbook/Podcast_summarizer_Agents/config/agents.yaml
  cookbook/Podcast_summarizer_Agents/config/tasks.yaml
  cookbook/Podcast_summarizer_Agents/images/Slack_message.png
  cookbook/Podcast_summarizer_Agents/images/test_run.png
  cookbook/Podcast_summarizer_Agents/main.py
  cookbook/Podcast_summarizer_Agents/requirements.txt
Labels: documentation, enhancement, Review effort [1-5]: 4

#307 feat: js sdk workspace support
  js/.DS_Store
  js/examples/langchain/demo.mjs
  js/examples/langchain/pnpm-lock.yaml
  js/package.json
  js/pnpm-lock.yaml
  js/src/env/base.ts
  js/src/env/constants.ts
  js/src/env/docker/workspace.ts
  js/src/env/e2b/workspace.ts
  js/src/env/factory.ts
  js/src/frameworks/cloudflare.ts
  js/src/frameworks/langchain.ts
  js/src/frameworks/openai.ts
  js/src/index.ts
  js/src/sdk/base.toolset.ts
  js/src/sdk/client/core/OpenAPI.ts
  js/src/sdk/index.ts
  js/src/sdk/types.d.ts
  js/src/sdk/workspace.ts
  python/composio/client/enums/_action.py
  python/composio/client/enums/_app.py
  python/composio/server/api.py
  python/composio/tools/local/base/action.py
  python/composio/tools/local/sqltool/actions/sql_query.py
  python/plugins/langchain/langchain_demo.py
  python/swe/examples/crewai_agent/agent.py
Labels: enhancement, Review effort [1-5]: 4, Dependencies

#356 update: Add OPENAI_API_KEY key in .env.example of rag_agent example
  python/examples/rag_agent/.env.example
Labels: documentation, Review effort [1-5]: 1

#358 fix: types for cloudflare framework
  js/examples/ai-playground-main/pnpm-lock.yaml
  js/src/env/base.ts
  js/src/env/docker/workspace.ts
  js/src/env/e2b/workspace.ts
  js/src/utils/shared.ts
  js/wrangler.toml
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#360 feat: bump js release to 0.1.6
  js/package.json
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#362 Added SWE Docs
  docs/mint.json
  docs/swekit/benchmarks.mdx
  docs/swekit/custom-tools.mdx
  docs/swekit/introduction.mdx
  docs/swekit/workspace-env.mdx
Labels: documentation, Review effort [1-5]: 1

#363 fix file manager and agent templates
  python/composio/cli/serve.py
  python/composio/client/enums/_action.py
  python/composio/client/enums/_tag.py
  python/composio/client/enums/_trigger.py
  python/composio/tools/env/filemanager/file.py
  python/composio/tools/env/filemanager/manager.py
  python/composio/tools/local/base/utils/utils.py
  python/composio/tools/local/codeindex/actions/create_index.py
  python/composio/tools/local/filetool/actions/__init__.py
  python/composio/tools/local/filetool/actions/edit.py
  python/composio/tools/local/filetool/actions/find.py
  python/composio/tools/local/filetool/actions/git_clone.py
  python/composio/tools/local/filetool/actions/git_patch.py
  python/composio/tools/local/filetool/actions/git_repo_tree.py
  python/composio/tools/local/filetool/actions/grep.py
  python/composio/tools/local/filetool/actions/open.py
  python/composio/tools/local/filetool/actions/scroll.py
  python/composio/tools/local/filetool/tool.py
  python/composio/tools/local/shelltool/shell_exec/actions/exec.py
  python/composio/tools/local/shelltool/shell_exec/actions/new.py
  python/swe/examples/crewai_agent/agent.py
  python/swe/examples/crewai_agent/main.py
  python/swe/swekit/agents/base.py
  python/swe/swekit/benchmark/run_evaluation.py
  python/swe/swekit/benchmark/utils.py
  python/swe/swekit/scaffold/templates/crewai/agent.template
  python/swe/swekit/scaffold/templates/crewai/inputs.template
  python/swe/swekit/scaffold/templates/crewai/main.template
  python/tests/test_tools/test_local/test_workspace.py
Labels: enhancement, Review effort [1-5]: 4, Bug fix, Possible security concern

#369 Fix edit tool, add runtime action
  python/composio/tools/env/filemanager/file.py
  python/swe/examples/crewai_agent/agent.py
  python/swe/swekit/benchmark/utils.py
  python/swe/swekit/scaffold/templates/crewai/agent.template
  python/tests/test_tools/test_local/test_workspace.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#373 Fix SWE accuracy
  python/composio/tools/env/filemanager/file.py
  python/composio/tools/env/filemanager/manager.py
  python/composio/tools/local/filetool/actions/chwdir.py
  python/composio/tools/local/filetool/actions/edit.py
  python/composio/tools/local/filetool/actions/git_patch.py
  python/composio/tools/local/filetool/actions/open.py
  python/composio/tools/local/filetool/actions/scroll.py
  python/dockerfiles/Dockerfile.dev
  python/dockerfiles/entrypoint.sh
  python/swe/examples/crewai_agent/agent.py
  python/swe/examples/crewai_agent/benchmark.py
  python/swe/swekit/benchmark/run_evaluation.py
  python/swe/swekit/benchmark/utils.py
  python/tests/test_tools/test_local/test_workspace.py
Labels: documentation, enhancement, Review effort [1-5]: 4, Bug fix

#371 Update README.md fix typo
  README.md
Labels: documentation, Review effort [1-5]: 1
