Repository ComposioHQ/composio, pull requests merged in 2024-06, with the labels that each got.

#91 Add trigger error
  composio/cli/triggers.py
Labels: Review effort [1-5]: 2, Bug fix

#94 feat: better help text
  composio/cli/__init__.py
  composio/cli/actions.py
  composio/cli/add.py
  composio/cli/apps.py
  composio/cli/connections.py
  composio/cli/integrations.py
  composio/cli/login.py
  composio/cli/logout.py
  composio/cli/triggers.py
  composio/cli/utils/helpfulcmd.py
  composio/cli/whoami.py
Labels: Review effort [1-5]: 3

#102 Added fallback type string
  composio/utils/shared.py
Labels: Review effort [1-5]: 2, Bug fix

#104 chore: show key instead of names in composio apps
  composio/cli/apps.py
Labels: enhancement, Review effort [1-5]: 1

#90 Update adding-local-tool.md
  docs/adding-local-tool.md
Labels: documentation, Review effort [1-5]: 1

#105 Add license and security policy
  Dockerfile
  LICENSE
  README.md
  SECURITY.MD
  scripts/upload_libs.sh
  start_cli.py
  tests/package.json
  tests/playwright.config.ts
  tests/pnpm-lock.yaml
  tests/session.json
Labels: documentation, enhancement, Tests, Review effort [1-5]: 4

#101 feat: add unexpected error tracking in sentry
  Pipfile
  composio/cli/__init__.py
  composio/cli/actions.py
  composio/core/cls/catch_all_exceptions.py
  composio/core/cls/did_you_mean.py
  setup.py
Labels: enhancement, Review effort [1-5]: 2, Dependencies

#100 feat: include local_workspace config directory in the distribution
  composio/local_tools/local_workspace/config/commands/__init__.py
  setup.py
Labels: enhancement, Review effort [1-5]: 2

#109 fix readme
  README.md
Labels: documentation, Review effort [1-5]: 2

#112 fixed logo in dark mode
  README.md
Labels: documentation, Review effort [1-5]: 1

#114 feat: bump to 0.3.9-rc.2
  plugins/autogen/setup.py
  plugins/claude/setup.py
  plugins/crew_ai/setup.py
  plugins/griptape/setup.py
  plugins/julep/setup.py
  plugins/langchain/setup.py
  plugins/lyzr/setup.py
  plugins/openai/setup.py
  setup.py
Labels: enhancement, Review effort [1-5]: 2

#116 fix: add init in utils
  composio/cli/__init__.py
  composio/cli/utils/__init__.py
Labels: enhancement, Review effort [1-5]: 2

#97 feat: add tests for examples back
  plugins/autogen/autogen_demo.py
  plugins/langchain/langchain_demo.py
  tests/core.spec.ts
  tests/global.setup.ts
  tests/global.teardown.ts
  tests/initial.spec.ts
  tests/test_cli/test_login.py
  tests/test_examples/__init__.py
  tests/test_examples/test_autogen.py
  tests/test_examples/test_langchain.py
Labels: enhancement, Review effort [1-5]: 2, Tests

#95 Handle local file upload [ENG-815]
  composio/client/__init__.py
  composio/core/local/action.py
  composio/local_tools/mathematical/actions/calculator.py
  composio/local_tools/ragtool/actions/rag_add_request.py
  composio/utils/shared.py
  examples/local_tools/langchain_math.py
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#113 Handle download response in file [ENG-800]
  composio/constants.py
  composio/tools/__init__.py
  examples/local_tools/langchain_math.py
  plugins/autogen/composio_autogen/toolset.py
  plugins/claude/composio_claude/toolset.py
  plugins/griptape/composio_griptape/toolset.py
  plugins/julep/composio_julep/toolset.py
  plugins/langchain/composio_langchain/toolset.py
  plugins/lyzr/composio_lyzr/toolset.py
  plugins/openai/composio_openai/toolset.py
Labels: enhancement, Review effort [1-5]: 3

#140 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report_frontend.md
  .github/ISSUE_TEMPLATE/bug_report_sdk.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, Review effort [1-5]: 2

#169 Fix trigger base model type handling
  composio/client/collections.py
  composio/client/enums.py
Labels: Review effort [1-5]: 2, Bug fix

#170 Handle local tools without API Key [ENG-900]
  composio/client/local_handler.py
  composio/tools/__init__.py
  plugins/autogen/composio_autogen/toolset.py
  plugins/claude/composio_claude/toolset.py
  plugins/griptape/composio_griptape/toolset.py
  plugins/langchain/composio_langchain/toolset.py
  plugins/lyzr/composio_lyzr/toolset.py
  plugins/openai/composio_openai/toolset.py
  tests/test_example.py
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#160 fix/157
  .gitignore
  composio/client/enums.py
  composio/client/local_handler.py
  composio/local_tools/filetool/__init__.py
  composio/local_tools/filetool/actions/__init__.py
  composio/local_tools/filetool/actions/read_file.py
  composio/local_tools/filetool/actions/write_file.py
  composio/local_tools/filetool/tool.py
  composio/local_tools/sqltool/__init__.py
  composio/local_tools/sqltool/actions/__init__.py
  composio/local_tools/sqltool/actions/sql_query.py
  composio/local_tools/sqltool/tool.py
  examples/benchmark/evaluation.py
  examples/investment_analysis/main.py
  examples/local_tools/langchain_math.py
  examples/news_summary/main.py
  examples/news_summary/readme.md
  examples/research_assistant/main.py
  examples/sql_agent/.env.example
  examples/sql_agent/company.db
  examples/sql_agent/log.txt
  examples/sql_agent/main.py
  examples/sql_agent/readme.md
  examples/sql_agent/requirements.txt
  examples/sql_agent/setup.sh
  examples/swe/benchmark_script.py
  examples/swe/evaluation/evaluation.py
  examples/swe/evaluation/run_evaluation.py
  examples/swe/evaluation/run_on_single_issue.py
  examples/swe/evaluation/visualize.py
  examples/swe/try-swe.py
Labels: documentation, Review effort [1-5]: 1

#174 Add CI chart
  composio/client/collections.py
  composio/client/enums.py
  composio/tools/__init__.py
  examples/crewai_ci_chart.py
Labels: enhancement, Tests, Review effort [1-5]: 4

#175 Change version
  plugins/autogen/setup.py
  plugins/claude/setup.py
  plugins/crew_ai/setup.py
  plugins/griptape/setup.py
  plugins/julep/setup.py
  plugins/langchain/setup.py
  plugins/llamaindex/setup.py
  plugins/lyzr/setup.py
  plugins/openai/setup.py
  setup.py
Labels: enhancement, Review effort [1-5]: 1

#180 Restructure composio SWE
  composio_swe/README.md
  composio_swe/__init__.py
  composio_swe/benchmark/run_evaluation.py
  composio_swe/composio_swe/__init__.py
  composio_swe/composio_swe/agent/__init__.py
  composio_swe/composio_swe/agent/swe.py
  composio_swe/composio_swe/cli/__init__.py
  composio_swe/composio_swe/cli/cli.py
  composio_swe/composio_swe/cli/tests/test_cli.py
  composio_swe/composio_swe/config/__init__.py
  composio_swe/composio_swe/config/config_store.py
  composio_swe/composio_swe/config/constants.py
  composio_swe/composio_swe/config/context.py
  composio_swe/setup.py
  tox.ini
Labels: enhancement, Tests, Review effort [1-5]: 3

#189 fix: Update README.md for logo
  README.md
Labels: documentation, Review effort [1-5]: 1

#197 Make req and resp any
  python/composio/client/collections.py
  python/composio/tools/__init__.py
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#198 Make swe simple to edit
  python/composio/local_tools/local_workspace/submit_patch/actions/submit_patch.py
  python/composio_swe/composio_swe/agent/README.md
  python/composio_swe/composio_swe/agent/prompts.py
  python/composio_swe/composio_swe/agent/swe.py
  python/composio_swe/composio_swe/agent/swe_run.py
Labels: documentation, enhancement, Review effort [1-5]: 3

#194 fix/177
  python/examples/sql_agent/readme.md
  python/examples/sql_agent/sql_agent_plotter_crewai/readme.md
  python/examples/sql_agent/sql_agent_plotter_llama_index/main.py
  python/examples/sql_agent/sql_agent_plotter_llama_index/readme.md
  python/examples/sql_agent/sql_agent_plotter_llama_index/requirements.txt
Labels: documentation, enhancement, Review effort [1-5]: 2

#202 Solve the patch issue
  python/Makefile
  python/composio/client/collections.py
  python/composio_swe/benchmark/run_evaluation.py
  python/composio_swe/composio_swe/agent/swe.py
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#204 Restructre SWE Agent
  python/composio/client/enums.py
  python/composio/local_tools/local_workspace/cmd_manager/actions/__init__.py
  python/composio/local_tools/local_workspace/cmd_manager/actions/clone_github.py
  python/composio/local_tools/local_workspace/cmd_manager/actions/get_patch.py
  python/composio/local_tools/local_workspace/cmd_manager/actions/git_tree.py
  python/composio/local_tools/local_workspace/cmd_manager/tool.py
  python/composio/local_tools/local_workspace/submit_patch/actions/submit_patch.py
  python/composio_swe/benchmark/get_scores.py
  python/composio_swe/benchmark/run_evaluation.py
  python/composio_swe/composio_swe/agent/README.md
  python/composio_swe/composio_swe/agent/base_swe_agent.py
  python/composio_swe/composio_swe/agent/prompts.py
  python/composio_swe/composio_swe/agent/requirements.txt
  python/composio_swe/composio_swe/agent/swe.py
  python/composio_swe/composio_swe/agent/swe_run.py
  python/composio_swe/composio_swe/agent/utils.py
  python/composio_swe/composio_swe/cli/cli.py
Labels: documentation, enhancement, Review effort [1-5]: 4

#214 Add test for swe actions
  python/composio/local_tools/local_workspace/cmd_manager/actions/clone_github.py
  python/composio/local_tools/local_workspace/tests/test_workspace.py
  python/examples/swe/evaluation/visualize.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#218 Improve SWE Accuracy
  .vscode/settings.json
  python/composio/local_tools/local_workspace/cmd_manager/actions/get_patch.py
  python/composio/local_tools/local_workspace/workspace/actions/create_workspace.py
  python/composio_swe/benchmark/complete_eval_workflow.sh
  python/composio_swe/benchmark/run_eval.md
  python/composio_swe/benchmark/run_evaluation.py
  python/composio_swe/composio_swe/agent/utils.py
  python/composio_swe/composio_swe/config/context.py
Labels: enhancement, Tests, Review effort [1-5]: 4

#219 Refactor SWE Agent code
  python/composio_swe/benchmark/run_evaluation.py
  python/composio_swe/composio_swe/agent/base_swe_agent.py
  python/composio_swe/composio_swe/agent/crewai.py
  python/composio_swe/composio_swe/agent/llama.py
  python/composio_swe/composio_swe/agent/swe.py
  python/composio_swe/composio_swe/agent/swe_run.py
  python/composio_swe/composio_swe/agent/utils.py
  python/composio_swe/composio_swe/cli/cli.py
Labels: enhancement, Review effort [1-5]: 4, other

#226 add cookbook
  cookbook/readme.md
Labels: documentation, Review effort [1-5]: 2

#230 Avoid Composio API Key in SWE
  python/composio/client/__init__.py
  python/composio/exceptions.py
  python/composio/tools/__init__.py
  python/swe/composio_swe/agent/base_swe_agent.py
  python/tests/test_client/test_client.py
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#239 Create .gitattributes
  .gitattributes
Labels: Review effort [1-5]: 1, Configuration changes
